stages:
- analysis


sonarqube:
  stage: analysis
  image: registry.git.rwth-aachen.de/ebc/ebc_all/gitlab-sonar-scanner:latest
  variables:
    SONAR_URL: http://137.226.248.164:9000
    SONAR_ANALYSIS_MODE: preview
  script:
  - gitlab-sonar-scanner
  # -Dsonar.issuesReport.console.enable=true -Dsonar.issuesReport.html.enable=true
  
sonarqube_report:
  stage: analysis
  image: registry.git.rwth-aachen.de/ebc/ebc_all/gitlab-sonar-scanner:latest
  variables:
    SONAR_URL: http://137.226.248.164:9000
    SONAR_ANALYSIS_MODE: publish
#    SONAR_PROJECT_KEY: modelica-calibration
#  only:
#    - master
  script:
    - gitlab-sonar-scanner
#    - sonar-scanner -Dsonar.host.url=$SONAR_URL -Dsonar.gitlab.commit_sha=${CI_COMMIT_SHA} -Dsonar.gitlab.ref_name=${CI_COMMIT_REF_NAME} -Dsonar.analysis.mode=$SONAR_ANALYSIS_MODE  -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.issuesReport.console.enable=true
