stages:
  - doc
  - code_quality
  - test
  - deploy

include:
  - project: 'EBC/EBC_all/gitlab_ci/templates'
    file: 'pylint.gitlab-ci.yml'
  - project: 'EBC/EBC_all/gitlab_ci/templates'
    file: 'sphinxdoc/sphinxdoc.gitlab-ci.yml'
  - project: 'EBC/EBC_all/gitlab_ci/templates'
    file: 'pages/pages.gitlab-ci.yml'
  - project: 'EBC/EBC_all/gitlab_ci/templates'
    file: 'tests/tests.gitlab-ci.yml'
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
