from setuptools import setup

setup(name='ebccalibration',
      version='0.1',
      description='Calibration helper',
      url='not set yet',
      author='RWTH Aachen University, E.ON Energy Research Center, Institute\
      of Energy Efficient Buildings and Indoor Climate',
      packages=['ebcpython',
                'ebcpython.basefunctions',
                'ebcpython.clustering',
                'ebcpython.graphics',
                'ebcpython.HDF5',
                'ebcpython.modelica',
                'ebcpython.occupancy',
                'ebcpython.sandbox',
				'ebcpython.MultiSourceDataHandler'],
      setup_requires=['mysql-connector-python>=8.0.11',
					'PyQt5>=5.6.2',
					'mwparserfromhell>=0.5.1',
					'mwclient>=0.8.7',
					'buildingspy>=1.7.0',
					'tables>=3.4.3',
					'influxdb>=5.2.0',
					'modelicares',
					'matplotlib'],

      install_requires=['mysql-connector-python>=8.0.11',
						'PyQt5>=5.6.2',
						'mwparserfromhell>=0.5.1',
						'mwclient>=0.8.7',
						'buildingspy>=1.7.0',
						'tables>=3.4.3',
						'influxdb>=5.2.0',
						'modelicares',
						'matplotlib'])
